libsemigroups/libsemigroups_pybind11

setup.py
This PR removes a comment's reference to `cppyy`.
=> Remove reference to `cppyy`

docs/source/presentations/present.rst
This PR adds some information to the documentation concerning the member function `contains_empty_word` and whether or not a presentation contains the empty word in any of its rules, as mentioned in a comment in #52.
=> Add explanation relating to `contains_empty_word`

src/cong.cpp, tests/test_cong.py
This adds a missing header (`chrono.h` from pybind11) to `cong.cpp` so that `C.run_for(timedelta(seconds=1))` and similar will work.
=> Add missing header include in cong.cpp

docs/source/presentations/present-helpers.rst, libsemigroups_pybind11/presentation.py, libsemigroups_pybind11/tools.py, src/present.cpp, tests/test_present.py
This PR adds functionality for the presentation helper function `replace_word`. In addition, some mistakes/omissions in the existing presentation helpers documentation are corrected.
=> Add functionality for the presentation helper `replace_word`

docs/source/api/fpsemi-examples.rst, docs/source/fpsemigroups.rst, libsemigroups_pybind11/fpsemigroup.py, src/fpsemi-examples.cpp, src/main.cpp, src/main.hpp, tests/test_fpsemi_examples.py
**Note: This PR is on top of #84**
This PR adds functionality for the `fpsemi-examples` presentations, addressing issue #83. It is not entirely finished, but in a state where @james-d-mitchell and I might discuss finishing touches. This might include:
- I haven't yet documented addition on the author values, since I'm not sure how this should look.
- There is a bug, I think possibly related to setting default author values, which I'll describe in a comment below. I've kept the default author value for `symmetric_group`, but not set this up for other functions yet. I'll do this after we've figured out what's going on.
- I will also double check everything's in order (mainly the documentation) before marking this as ready for review.
=> Add functionality for the `fpsemi-examples` presentations

docs/source/api/toddcoxeter.rst, src/todd-coxeter.cpp, tests/test_todd_coxeter.py
This PR adds functionality for the `ToddCoxeter` function `to_gap_string`.
I think the CI will fail until there is a release of `libsemigroups` which includes the PR which adds argument checking for the sidedness of the congruence.
=> Add functionality for `ToddCoxeter` function `to_gap_string`

libsemigroups_pybind11/action_digraph_helper.py, tests/test_actiondigraph.py
This PR improves the `graphviz` colour capability for `ActionDigraph` objects, as discussed in issue #100.
More specifically: a nice palate of nine colourblind accessible colours due to [Paul Tol](https://personal.sron.nl/~pault/) is used. Where a graph has more than nine distinct labels whose edges need coloured, these nine colours are simply reused cyclically. This seemed like a reasonable way of doing things.
=> Improve `ActionDigraph` `graphviz` colour capability

Makefile, docs/source/conf.py
This PR:
* adds  `make doctest` functionality, that was previously only available inside the `docs/` folder.;
* adds `doctest` to the `make check` recipe; and
* changes how type replacement is done.
=> Update type replacement and doctest

docs/source/api/digraph-helper.rst, libsemigroups_pybind11/word_graph.py, src/forest.cpp, tests/test_gabow.py, tests/test_paths.py, tests/test_wordgraph.py
This PR adds some tests for the mentioned stuff, which seemed to get lost in some earlier merging.
=> Add tests for `Gabow`, `WordGraph` and `Paths`

docs/source/conf.py, docs/source/reporter.rst, docs/source/runner.rst, requirements.txt
Supersedes https://github.com/james-d-mitchell/libsemigroups_pybind11/pull/3. In this PR, the new directive is used in the documentation of `Reporter` and `Runner`.
=> Add extended docstring directive

Makefile, docs/source/conf.py, docs/source/data-structures/misc/reporter.rst, docs/source/data-structures/misc/runner.rst
This PR improves how overloaded functions get rendered in the documentation. Specifically, it formats them in the same that non-overloaded functions get formatted, and adds a level of indentation.
I decided to use this directive to override the standard `autoclass` and `autofunction` directives, since it provides a superset of their functionality. The only downside that I can see is that this causes a `directive already registered` warning. If this is undesirable I can call it something else.
=> Update the autodoc directive to improve overloaded functions

docs/source/conf.py, docs/source/main-algorithms/knuth-bendix/kb-helpers.rst, etc/replace-strings-in-doc.py, src/knuth-bendix.cpp
This PR introduces the option `:only-document-once:`. Any docstring that starts with this option will only appear once in that functions entry in the documentation, even if that function is overloaded. This is useful when overloaded functions get created as a consequence of types hidden from the user.
In order to specify what the signature of the overloaded function should be (instead of the default `(*args, **kwargs)`), you can specify `:sig=<NEW_SIGNATURE>:` before the `:only-document-once:` option.
=> Add only-document-once option

CONTRIBUTING.rst, dev-environment.yml, etc/make-dev-environment.sh, etc/set-conda-environment-variables.sh
This PR adds a script that can be sourced to create and activate an environment with the packages and environment variables necessary to develop `libsemigroups_pybind11`.
I had originally hoped that this would be possible using conda, mamba or micromamba. Unfortunately, micromamba doesn't presently support the feature to add environment variables for specific envs, so only conda and mamba are supported.
The contributing guide has also been updated to reflect how a developer should go about setting up their working environment.
=> Create an environment for developing

docs/source/data-structures/constants/index.rst, docs/source/index.rst
To reduce the number of warnings produced by `make doc`, this PR adds documentation for some constants.
It wasn't entirely clear where this should be placed in the docs. Data Structures seemed to make the most sense, but I'm happy to move it if there is a better suggestion.
=> Add doc for constants

src/aho-corasick.cpp
This PR moves the documentation of active nodes to the class description, inline with https://github.com/libsemigroups/libsemigroups/pull/574.
This should remain a draft until that PR is finalised and merged.
=> Update AhoCorasick doc

src/aho-corasick.cpp, src/present.cpp, src/runner.cpp, src/to_presentation.cpp, src/transf.cpp, src/words.cpp
This PR removes instances of `This function guarantees not to throw a ``LibsemigroupsError``.` and `This function is guaranteed never to throw.`
=> Remove no-excepts

CONTRIBUTING.rst, docs/source/conf.py, etc/replace-strings-in-doc.py
This PR fixes some issues relating to function names.
Firstly, this PR ensures that all overloads of a function have the same name in the doc. If one were to do 
```py
from _libsemigroups import pbr_one as one
```
the doc would look something like:
> one()
pbr_one(*args, **kwargs)
Overloaded function.
>> pbr_one(n: int)
> [...]
>> pbr_one(x: PBR)
> [...]
which is not good. After this PR, they would all appear as `one` 
Secondly, as illustrated in the example above, signatures sometimes get inserted into the doc-string. Previously, we were fixing this by removing them from the html post-build. Unfortunately, if that signature contains `(*agrs, **kwargs)`, bad things happen during the build process since sphinx interprets the `*`s as special charters. This PR fixes that by providing a means …
=> Fix function names

src/CPPLINT.cfg
On 06/10/24, `cpplint` released version 2.0.0. Amongst [other changes](https://github.com/cpplint/cpplint/blob/develop/CHANGELOG.rst), this seemingly changed some of the names of the filters. This PR updates the names of our filters, and puts them in alphabetical order.
=> Update cpplint config

docs/source/data-structures/misc/constants.rst, docs/source/data-structures/word-graph/paths/paths.rst, libsemigroups_pybind11/__init__.py, libsemigroups_pybind11/detail/decorators.py, libsemigroups_pybind11/paths.py, src/paths.cpp
This PR updates the `Paths` class. Specifically, it defines some decorators, one of which allows a function to return `POSITIVE_INFINITY`. Furthermore, it documents the classes of each of the constants we define, so that more types in function signatures get converted to URLs.
=> Handle returning `POSITIVE_INFINITY` in `Paths`

docs/source/data-structures/misc/index.rst, docs/source/data-structures/misc/libsemigroups-error.rst, src/main.cpp
This PR adds `LibsemigroupsError` to the doc, so now every time we write `:raises LibsemigroupsError` in a docstring, at makes a nice link :)
=> Add `LibsemigroupsError` to the doc

docs/source/conf.py, docs/source/index.rst, docs/source/main-algorithms/schreier-sims/index.rst, docs/source/main-algorithms/schreier-sims/schreier-sims-helpers.rst, docs/source/main-algorithms/schreier-sims/schreier-sims.rst, etc/replace-strings-in-doc.py, libsemigroups_pybind11/__init__.py, libsemigroups_pybind11/action.py, libsemigroups_pybind11/adapters.py, libsemigroups_pybind11/detail/cxx_wrapper.py, libsemigroups_pybind11/froidure_pin.py, libsemigroups_pybind11/schreier_sims.py, src/main.cpp, src/main.hpp, src/schreier-sims.cpp, tests/test_schreier_sims.py
This PR adds the `SchreierSims` class and associated helpers in advance of the v1 release. Supersedes #109.
=> Add `SchreierSims` for v1

requirements.txt, src/aho-corasick.cpp, src/kambites.cpp, src/knuth-bendix.cpp, src/obvinf.cpp, src/present.cpp, src/schreier-sims.cpp, src/todd-coxeter.cpp, src/words.cpp
This PR makes some minor changes to the doc. Primarily, it fixes the documentation for some overloaded constructors and `init` functions, and resolves from broken links.
=> Minor doc fixes

src/transf.cpp
This PR updates the bindings to reflect the changes made in https://github.com/libsemigroups/libsemigroups/pull/629
=> Change `make::Thing` -> `to<Thing>` for the `PTransf` functions

src/aho-corasick.cpp, src/bmat8.cpp
This will likely fail the CI until #216 is merged.
=> Rename to_string -> to_human_readable_repr for BMat8 + AhoCorasick

src/cong-common.cpp, src/cong.cpp
This PR implements the Pybind analogue of the changes in https://github.com/libsemigroups/libsemigroups/pull/667
=> Make `add_generating_pair` return `None`

src/froidure-pin.cpp, src/present.cpp
This PR fixes the return types following from https://github.com/libsemigroups/libsemigroups/pull/672
=> Fix return types

pyproject.toml
This is an attempt to fix the issue described here:
https://github.com/libsemigroups/libsemigroups/pull/698
The fact that the version of setuptools is specified in two separate places (requirements.txt and pyproject.toml) is concerning, but maybe we can address that later.
=> Pin setuptools version in pyproject.toml

.github/workflows/tests.yml
This PR updates the ci to use the `stable-3.0` branch of `libsemigroups`.
=> Update ci to use the `stable-3.0` branch of `libsemigroups`

docs/source/data-structures/presentations/to-inverse-present.rst, docs/source/data-structures/presentations/to-present.rst, docs/source/data-structures/to-function.rst, docs/source/main-algorithms/froidure-pin/to-froidure-pin.rst, docs/source/main-algorithms/knuth-bendix/to-knuth-bendix.rst, docs/source/main-algorithms/todd-coxeter/to-todd-coxeter.rst, src/libsemigroups_pybind11/to.py, src/to-presentation.cpp, tests/test_to.py
This PR consists of a minor refactor of the `to` function that removes unnecessary lambdas, and adds the option to convert a `KnuthBendix` object to a `Presentation` over words with a specified type.
=> Convert from `KnuthBendix` and a word type to a `Presentation`.

docs/source/conf.py, docs/source/data-structures/misc/libsemigroups-error.rst, docs/source/index.rst, etc/replace-strings-in-doc.py, src/action.cpp, src/adapters.cpp, src/dot.cpp, src/errors.cpp, src/froidure-pin.cpp, src/libsemigroups_pybind11/action.py, src/libsemigroups_pybind11/adapters.py, src/libsemigroups_pybind11/detail/cxx_wrapper.py, src/libsemigroups_pybind11/froidure_pin.py, src/libsemigroups_pybind11/konieczny.py, src/libsemigroups_pybind11/presentation/__init__.py, src/libsemigroups_pybind11/schreier_sims.py, src/libsemigroups_pybind11/stephen.py, src/matrix.cpp, src/report.cpp, src/word-range.cpp, tests/test_schreier_sims.py, tests/test_words.py
This PR ensures the correct errors are being thrown, and that we document the errors that actually get thrown. It also updates how we register our custom `LibsemigroupsError` to move away from some deprecated functions.
There are a few places where we arguably throw the wrong error (for example, we throw a `LibsemigroupsError` rather than a `ValueError` when trying to add a generator to a `FroidurePin` with the wrong degree). We could fix this, but this seems like more hassle than it's worth.
=> Use the correct error types

src/knuth-bendix.cpp
This PR moves the binding of `knuth_bendix_redundant_rule` out of the function template `bind_knuth_bendix` since the it doesn't depend on the template parameters.
=> Don't bind `redundant_rull` too many times

src/todd-coxeter-impl.cpp
This PR documents the `ToddCoxeter.options` enums like `tril`.
=> doc: Document ToddCoxeter enums like tril

docs/source/data-structures/elements/matrix/matrix.rst, docs/source/install.rst, src/libsemigroups_pybind11/matrix.py
Seems to have been accidentally removed.
=> doc: readd MatrixKind doc

docs/source/_ext/libsemigroups_pybind11_extensions.py, docs/source/conf.py, docs/source/main-algorithms/core-classes/runner.rst, docs/source/main-algorithms/knuth-bendix/helpers.rst, docs/source/main-algorithms/schreier-sims/class.rst, src/action.cpp, src/bmat8.cpp, src/forest.cpp, src/froidure-pin-base.cpp, src/froidure-pin.cpp, src/knuth-bendix-impl.cpp, src/konieczny.cpp, src/libsemigroups_pybind11/action.py, src/libsemigroups_pybind11/sims.py, src/matrix.cpp, src/present.cpp, src/report.cpp, src/runner.cpp, src/sims.cpp, src/todd-coxeter.cpp, src/word-graph.cpp, src/word-range.cpp
This PR enables the Sphinx config option `nitpicky`, and addresses any resultant warnings. In `nitpicky` mode, Sphinx will warn about all references where the target cannot be found.
Additionally, this PR updates `conf.py`. Unused options have been removed, each setting has an explanation, and the options are ordered in the same way as they are in the sphinx documentation.
=> Doc: Enable nitpicky

src/knuth-bendix-impl.cpp, src/knuth-bendix.cpp
Due to changes in KnuthBendixImpl in libsemigroups itself.
=> knuth-bendix: move functionality from impl

docs/source/_ext/libsemigroups_pybind11_extensions.py, src/main.cpp, src/sims.cpp
This PR does two things:
1. Refactor the sims binding code so that subclasses do not incorrectly override (rather than overload) certain functions (addressing #305) ; and
2. Change the order in which things are initialized. This reduces the amount of C++ style code that appears in the error messages, amongst other places.
=> Fix subclass overrides and initialization order

tests/test_cong.py
Namely the changes in 
https://github.com/libsemigroups/libsemigroups/pull/790
that check `is_obviously_infinite` before trying to return the `number_of_classes`.
=> tests: update after libsemigroups changes
